### ISSUE TITLE
Pictures rotating

### ISSUE THREAD

**Issue by capedra** [danielgatis/rembg#13]
@danielgatis 
Hello, most of my pictures have been rotating to the right (90 degrees) after removing their backgrounds. Does anyone know how to solve this issue? Thanks a lot!
Down below, I attach one of the pictures that I face this issue:

Original:
![NIVEA Creme Original](https://i.ibb.co/5sSxrkZ/IMG-0861.jpg)

Without background:
![NIVEA Creme Rotated](https://i.ibb.co/h72MR5j/1A.png)

**Comment by danielgatis** [comment]
Hello @capedra. I was unable to reproduce the bug here. Probably the rotation is being caused by another program after removing the background.

I just run:

```
rembg ~/Desktop/a.jpeg > ~/Desktop/b.png
```

<img width="159" alt="Captura de Tela 2020-09-28 às 10 36 38" src="https://user-images.githubusercontent.com/7380/94439211-825f8980-0176-11eb-8601-fbba2f65bd07.png">

**Comment by ondrejbartas** [comment]
@capedra look at metadata (exif data) maybe your original images are rotated because of them and rembg is just ignoring them.

**Comment by chunchaolo** [comment]
If photo has orientation tag – rotate it.
[https://stackoverflow.com/questions/13872331/rotating-an-image-with-orientation-specified-in-exif-using-python-without-pil-in](https://stackoverflow.com/questions/13872331/rotating-an-image-with-orientation-specified-in-exif-using-python-without-pil-in)
