### ISSUE TITLE
error when input file is jpg, and png is ok

### ISSUE THREAD

**Issue by badboy-tian** [danielgatis/rembg#151]
```
Traceback (most recent call last):
  File "/tmp/card/rembg/app.py", line 16, in <module>
    result = remove(f)
  File "/tmp/card/rembg/src/rembg/bg.py", line 91, in remove
    img = Image.open(io.BytesIO(data)).convert("RGB")
  File "/tmp/card/rembg/deps/PIL/Image.py", line 915, in convert
    self.load()
  File "/tmp/card/rembg/deps/PIL/ImageFile.py", line 249, in load
    raise OSError(
OSError: image file is truncated (5 bytes not processed)
```

```
from rembg.bg import remove
import numpy as np
import io
from PIL import Image

print("1")
input_path = '/tmp/card/rembg/animal-1.jpg'
output_path = '/tmp/card/rembg/out.png'

f = np.fromfile(input_path)
print("2")
result = remove(f)
print("3")
img = Image.open(io.BytesIO(result)).convert("RGBA")
print("4")
img.save(output_path)
print("5")
```

**Comment by Lunarelements** [comment]
Just gonna drop this here because I ran across it myself, this line is is how I fixed this:
`ImageFile.LOAD_TRUNCATED_IMAGES = True`

The explanation of why this works can be found here: https://stackoverflow.com/questions/26776454/working-with-truncated-images-with-pil

So it will look something like this:
`
from rembg.bg import remove
import numpy as np
import io
from PIL import Image
from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True

f = np.fromfile(input_path)
result = remove(f)
img = Image.open(io.BytesIO(result)).convert("RGB")
img.save(output_path)
`
