### ISSUE TITLE
Run as cloud service. Lambda?

### ISSUE THREAD

**Issue by jcroucher** [danielgatis/rembg#246]
Has anyone been able to get this working in something like Lambda?

**Comment by niteshanandan** [comment]
@jcroucher were you able to get this working?

**Comment by jcroucher** [comment]
> @jcroucher were you able to get this working?

I did get it running but it was reloading the model on cold starts, making cold starts take around 20 minutes.
Even when it was working without a cold start, performance wasn't great. I couldn't afford to spend any more time on it so I had to go a different route.

**Comment by rnag** [comment]
@jcroucher In case it is helpful, I've created an almost identical project for AWS environments, [rembg-aws-lambda](https://github.com/rnag/rembg-aws-lambda). It strips down some code, such as dependencies, CLI, and downloading the `*.onnx` files. The PyPI package contains [`u2net.onnx`](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) already, so installing it or setting `U2NET_HOME` is not required anymore.

The project can be installed with:

```console
pip install rembg-aws-lambda
```

Re. the cold start issues, they should be eliminated by this variant package. I have done extensive testing before this previously, and determined that the cold start issue(s) to be primarly due to:
1) downloading the `*.onnx` files into the `/tmp` directory each time
2) import statement for `pymatting` - as this package heavily utilizes decorators such as `@njit`, which uses numba to cache function optimizations. As this saves it into `NUMBA_CACHE_DIR` which should ideally point to `/tmp` for AWS Lambda Docker images, this takes a lot of time on each cold start as `/tmp` directory is clean (empty) at this point.

Check it out and let me know if it works for your use case. See also: https://github.com/danielgatis/rembg/issues/373
