### ISSUE TITLE
Performance: Docker vs Library

### ISSUE THREAD

**Issue by echtme** [danielgatis/rembg#332]
Hi there. I'm running the rembg Dockerfile image (2.xx GB) on Google Cloud Run, which works pretty good. However, I've created a custom Docker image with Python-slim (0.5GB) to keep it ligther and used the rmbg library + Flask, with the same settings on Cloud Run, but surprisingly the larger rembg Docker Container is still much faster. How is this possible?   

Also, is there a way to define the model when using the rembg library?

I'm looking for ways to speed up the process and a lighter image to improve server cold starts.

**Comment by AlfredUFY** [comment]
Hi @echtme.
I use [rembg image](https://hub.docker.com/r/danielgatis/rembg) on local is ok, but get PORT error when I start it on Google Cloud Run ([issue 327](https://github.com/danielgatis/rembg/issues/327))

- I build [this](https://github.com/AlfredUFY/rbg/tree/ctnr) for Google Cloud Run, but it is slow when startup(more than 30s).
- I googled for this issue, and got some tips to [optimize Cloud Run response times](https://cloud.google.com/blog/topics/developers-practitioners/3-ways-optimize-cloud-run-response-times)and [this](https://cloud.google.com/run/docs/tips/python).
- And one more tip is to move large files outside of the container(.u2net models in this case)  like [this](https://blog.truaro.dev/improving-cloud-build-with-dependencies-cache/)

(Since I'm not a Python coder, I'm not sure if the above tips will work for you, just for reference.)

BTW, any tips for the [PORT error](https://github.com/danielgatis/rembg/issues/327) of [rembg image](https://hub.docker.com/r/danielgatis/rembg) on Google Cloud Run is appreciate!

**Comment by AlfredUFY** [comment]
Do you try to [move large files outside of the container](https://cloud.google.com/run/docs/tips/python#move_large_files_outside_of_the_container)? The .u2net folder is large than 0.5GB.

My [repo](https://github.com/AlfredUFY/rbg/tree/ctnr) costs more than 30s for cold start on Google Cloud Run.

BTW, I haven't tried moving large files out of the container. [PORT error](https://github.com/danielgatis/rembg/issues/327) when using [rembg image](https://hub.docker.com/r/danielgatis/rembg) on Google Cloud Run.

**Comment by echtme** [comment]
I'm only using the one generic u2net model, which is a little less than 200mb if I remember correctly. But I would prefer to have it as part of the image rather than downloading every time when the container start up.

Regarding the cold starts, you can run a minimum instance, or setup a cron job and ping it every few minutes. Which is much much cheaper and the same at the end.

**Comment by echtme** [comment]
Regarding the port error, make sure the flask/fast api and Dockerfile ports are matching. I had another instance where I got some dependencies error while compiling the Docker and Google was giving me a port error at the end. Doesn't makes sense, but when I've fixed the dependencies issue, it was working.

**Comment by Riz0** [comment]
Hi @echtme ,

Can you briefly explain how you managed to get the Dockerfile image (2.xx GB) to play nicely Google Cloud Run? Like @AlfredUFY , I too have that same port error despite doing very basic pulling of image (docker pull danielgatis/rembg), tagging and pushing to google container registry then creating service with rembg's default "5000" port. I don't see any dependency issues in log (I only pull the image not compile it), just the port issue. Any help is appreciated.

**Comment by echtme** [comment]
You have to adjust also the port in the Google Cloud console to 5000

**Comment by Riz0** [comment]
> You have to adjust also the port in the Google Cloud console to 5000

@echtme Thanks for the reply as I've been really struggling with this. Can you please tell me how to actually adjust the port so it allows the image to start effectively? Here is where I edited in the port when I initially created the service on Google Cloud run: 

![AwUJ9Ga](https://user-images.githubusercontent.com/3844296/214790602-dd418bca-1d17-4b2e-a622-425c54f15b09.png)

Here is what my current log looks like:
 
![2upU3VT](https://user-images.githubusercontent.com/3844296/214791414-63efdd50-56b8-42fc-a909-78e239b8d49c.png)

I was initially thinking it was a firewall issue as well, but apparently cloud run doesn’t really have firewall to adjust with like compute engine does so not sure how to change port settings otherwise from console. Thanks again for any help, I really appreciate it!

**Comment by echtme** [comment]
First make sure the server started. The last three line in the Docker file:
EXPOSE 5000
ENTRYPOINT ["rembg"]
CMD ["s"]

In the Google Cloud web interface go to "Google Cloud Run" of your project and "Edit and Deploy new Revision":
![1](https://user-images.githubusercontent.com/20922271/214796238-83e0db40-7426-43ba-b386-daef129bd69a.jpg)
![2](https://user-images.githubusercontent.com/20922271/214796250-25cfda94-6c36-4020-80f2-79bda332985b.jpg)

The first start takes some times, approx. 40 seconds but once the instance is warm, it's super fast.

**Comment by Riz0** [comment]
@echtme Thanks again for the explanation. Hm, I don't think it ever actually starts to completion as indicated by the missing url:

![DFs8mfP](https://user-images.githubusercontent.com/3844296/214801341-bf0fd46b-97f2-41d9-8223-369e6667b516.png)

Our container settings where I insert the port looks to be the same, but I notice that the last three lines of the docker file you mention are different then one in main branch currently:
https://github.com/danielgatis/rembg/blob/main/Dockerfile

EXPOSE 5000
ENTRYPOINT ["rembg"]
CMD ["--help"]

I've never actually edited the docker file, I simply pulled the stock latest image from here: https://hub.docker.com/r/danielgatis/rembg

Should I be downloading locally, editing the last three lines of docker file to reflect what you mention:

EXPOSE 5000
ENTRYPOINT ["rembg"]
CMD ["s"]

Then rebuild and push that to my project? Or can I override the docker file from google cloud console without having to rebuild docker file/image? Bit of a docker noob so not sure best way. I guess the default docker is just calling help then exiting instead of starting the http server with "CMD ["s"]" entry, right? If not, could you please advise what is the best approach. Thanks again for any help.

**Comment by echtme** [comment]
I've directly modified the .Docker file from the Github.
CMD ["s"] as per the docs starts the server, not sure why they've added --help.

**Comment by Riz0** [comment]
> I've directly modified the .Docker file from the Github. CMD ["s"] as per the docs starts the server, not sure why they've added --help.

That was it! Edited and rebuilt so it works now. Thanks so much! By the way how are you securing your curl requests to the rembg http server on GCR, apikey or some other setting? Wouldn't want it to get abused I suppose.
