### ISSUE TITLE
[BUG] ...ERROR: Cannot install rembg[gpu]==2.0.24 and rembg[gpu]==2.0.25 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by studiokevinabanto** [danielgatis/rembg#338]
I get this error when trying to install it: 

ERROR: Cannot install rembg[gpu]==2.0.24 and rembg[gpu]==2.0.25 because these package versions have conflicting dependencies.

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Known-Error** [comment]
I got the same error when trying to install it with python 3.11 and I installed with python 3.9 successfully

**Comment by darksean009** [comment]
> I got the same error when trying to install it with python 3.11 and I installed with python 3.9 successfully

Man, it really works, it helped me, thank you

**Comment by HenkHoden** [comment]
I got the same problem. fresh install so no old version @danielgatis

**Comment by kalkulusrampage** [comment]
i have the same problem, no previous versions just new fresh install

ERROR: Cannot install rembg==2.0.24 and rembg==2.0.25 because these package versions have conflicting dependencies.

The conflict is caused by:
    rembg 2.0.25 depends on numpy==1.21.6
    rembg 2.0.24 depends on numpy==1.21.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by danielgatis** [comment]
take a look:
https://github.com/danielgatis/rembg#installation
