### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by shersoni610** [danielgatis/rembg#357]
Hello 

I am running the software on a MAC machine ( Ventura OS). For the following command I get the message:

rembg -m u2netp i birds.jpg aa.png

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Usage: rembg [OPTIONS] COMMAND [ARGS]...
Try 'rembg --help' for help.

Error: No such option: -m

**Comment by marco-wd** [comment]
Also experiencing this in ubuntu.
Usage: rembg [OPTIONS] COMMAND [ARGS]... 
Try 'rembg --help' for help. Error: No such option: -m

**Comment by jangop** [comment]
Swap the order of `-m ...` and `i`. So, instead of

```bash
rembg -m u2netp i birds.jpg aa.png
```

execute

```bash
rembg i -m u2netp birds.jpg aa.png
```

@shersoni610 Please edit the title of this issue to clarify what problem you are facing.

@danielgatis The readme does provide `rembg -m u2netp i path/to/input.png path/to/output.png` as an example. Maybe that worked at some point and the behavior of `click` has since changed. 🤷

**Comment by shersoni610** [comment]
Thanks, but m close to model and -I close to input seem more intuitive. Wish it could be that way.

**Comment by danielgatis** [comment]
Guys, thank you so much! I updated the documentation.
