### ISSUE TITLE
[BUG] Not installed on Linux python 3.8

### ISSUE THREAD

**Issue by lokipointer** [danielgatis/rembg#376]
`python3.8 -m pip install rembg`
...
Collecting onnxruntime~=1.13.1 (from rembg)
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement onnxruntime~=1.13.1 (from rembg) (from versions: 1.2.0, 1.3.0)
No matching distribution found for onnxruntime~=1.13.1 (from rembg)

`python3.8 -m pip install onnxruntime`
Leads to another error.

**Comment by haichay88** [comment]
same error on window 10

ERROR: Cannot install rembg==2.0.28, rembg==2.0.29 and rembg==2.0.30 because these package versions have conflicting dependencies.

The conflict is caused by:
    rembg 2.0.30 depends on numpy~=1.23.5
    rembg 2.0.29 depends on numpy==1.23.5
    rembg 2.0.28 depends on numpy==1.23.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by lokipointer** [comment]
solved the problem
`python3.8 -m pip install --upgrade pip`
