### ISSUE TITLE
Output Size is almost 5x input size [FEATURE] ...

### ISSUE THREAD

**Issue by MoSala7** [danielgatis/rembg#391]
I like this tool so much but it has a major problem which is the image output size

First Case:
The input image size is 879KB with a resolution of 5184x3458
The output image size is 5.37MB with a resolution of 5184x3458

Second Case:
The input image size is 202KB with a resolution of 1920x1080
The output image size is 899KB with a resolution of 1920x1080

Is there any solution to reduce the output size and maintain the quality?

**Comment by ShehrozIrfan** [comment]
Hey @MoSala7 

I think you can use `ffmpeg` to reduce the size of the image.

**Comment by jangop** [comment]
Is this not simply about compression of images (with alpha channels)? Does not really seem to be an issue directly related to `rembg`.

**Comment by danpak6** [comment]
Hi @jangop,

If your input image format is JPEG and you convert it to PNG with an alpha channel, the resulting PNG file will typically be much larger than the original one. This is because JPEG is a lossy compression format that uses algorithms to reduce the file size by discarding some image information. At the same time, PNG is a lossless format that preserves all image data. Additionally, the alpha channel in PNG stores transparency information for each pixel, which can significantly increase the file size compared to JPEG.
