### ISSUE TITLE
[BUG] Permission error despite running on elevated permissions. (ONNX runtime error: 13)

### ISSUE THREAD

**Issue by Potato22** [danielgatis/rembg#477]
**Describe the bug**
ONNX returns permission error despite being run on an elevated process (Administrator)

**To Reproduce**

1. init and use rembg like usual.
2. wait.
3. see permission error: `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from C:\Users\potat\.u2net\u2net.onnx failed:system error number 13`

**Expected behavior**
rembg or ONNX should be able to read the path just fine.

**Images**
![image](https://github.com/danielgatis/rembg/assets/39096741/1722ad30-b089-47dd-883e-e07bb4aba1dd)

**OS Version:**
Windows 11 Pro for Workstations
22H2
22631.1900

**Rembg version:**
rembg, version 2.0.47

**Additional context**
-

**Comment by antscribano** [comment]
Similar error here after trying to install onnxruntime.

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Users\\anton\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sympy\\plotting\\tests\\test_region_and.png'

So I uninstalled rembg, Python, deleted any Python folder and tried to reinstall everything from scratch (while also clearing cache).

Now I can't event reinstall rembg

![image](https://github.com/danielgatis/rembg/assets/8087993/2514ba6d-38f2-40d2-8ce6-7cd850e64d68)

Also tried to reinstall sympy (4.1.0) with no luck and clear cache.

Running cmd as Admin. Windows 11 Pro 22631.2506 + Python 3.11.6

Please let me know if you prefer I open a brand new bug issue.

Thank you
