### ISSUE TITLE
why not support u2net-portrait-matting?

### ISSUE THREAD

**Issue by coollofty** [danielgatis/rembg#481]
Can u2net-portrait-matting be added to the support list as it has better separation of hair than u2net-human-seg?

**Comment by Chrescht** [comment]
I simply tried and it works, even though I am not getting the same very good results like 
https://www.photoroom.com/tools/background-remover
I take it the model for the background-remover has been trained to produce these nice results.

**Comment by pristugm** [comment]
@Chrescht Where did you find the model if i may ask? [https://github.com/dbpprt/u-2-net-portrait](/dbpprt/u-2-net-portrait) has a dead onedrive link, and I cant seem to find any other mirror for the model

**Comment by Chrescht** [comment]
I didn't find it anywhere, I just used `session = new_session("u2net-portrait-matting")` but I am not seeing any new onnx file in my personal .u2net folder. Maybe some default session is used instead? I have no idea, but since it produced ok results, I thought portrait matting was being used.
I'm probably wrong.

I did find a pre-trained model here though: https://github.com/axinc-ai/ailia-models
https://storage.googleapis.com/ailia-models/u2net-portrait-matting/u2net-portrait-matting.onnx
but I am not really getting it to work.

Currently I am getting the best results with u2net_human_seg and no alpha matting.
