### ISSUE TITLE
[FEATURE] Don't save models to user home for pip installations

### ISSUE THREAD

**Issue by ymgenesis** [danielgatis/rembg#517]
It would be beneficial to save the .onnx models in the `rembg` site-packages folder (perhaps in a 'models' folder), instead of a hidden directory in the user's home folder (which is a pretty bold move). That way nothing is saved outside of the project's package.

Furthermore, a `pip uninstall rembg` won't remove the `.u2net` from the user's home folder.

I've seen [this](https://github.com/danielgatis/rembg/issues/420) workaround to changing where the models are read from, but this doesn't change where the models are installed.

I'm building a node for InvokeAI with this tool to remove backgrounds, but am hesitant to release it as it saves model files outside of Python's environment.

Also, I noticed `isnet-general-use.onnx` isn't included when installing 2.0.50 from pip.

**Comment by hipsterusername** [comment]
Looking into rembg, I am wondering if we ought not just decompose that into it's parts, and focus on supporting the SoTA model for identification of background.

Specifically, we could revive the SAM-HQ node that was being worked on by @aluhrs13 (https://github.com/aluhrs13/iai_node_sam/blob/main/segment_anything_node.py) and then figure out if there are any missing functions in rembg that we actually want.

There otherwise seems to be a lot of bloat in rembg that we wouldn't be getting out of an individual node

**Comment by hipsterusername** [comment]
Bad GitHub actions bot, Bad!
