### ISSUE TITLE
[BUG] no module named onnxruntime

### ISSUE THREAD

**Issue by Zeit08** [danielgatis/rembg#528]
I installed the cpu version and ran it a week ago with a jpg file. All good. Now I tried with a png and it failed, output below.
I ran as usual `rembg i source destination`

### Output
`Traceback (most recent call last):
  File "/home/user/.local/bin/rembg", line 5, in <module>
    from rembg.cli import main
  File "/home/user/.local/lib/python3.11/site-packages/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "/home/user/.local/lib/python3.11/site-packages/rembg/bg.py", line 21, in <module>
    from .session_factory import new_session
  File "/home/user/.local/lib/python3.11/site-packages/rembg/session_factory.py", line 4, in <module>
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'
`

**OS Version:**
Fedora 38

**Rembg version:**
v2.0.50

What am I missing?

**Comment by dCo3lh0** [comment]
if using GPU
pip install onnxruntime-gpu

If using CPU
pip install onnxruntime

**Comment by devmanso** [comment]
May I ask what IDE you're using? 
This is because I was having a similar issue to yours, and I was using PyCharm. Sometimes reconfiguring the Virtualenv works, restarting the IDE, or installing it through the terminal.

If you installed your packages through the terminal, and they are still not being recognized, try letting PyCharm install it, by pressing Alt+Shift+Enter, or by hovering over the import line and clicking on the link that says "install package ...".

Hope this helps

**Comment by nantipov** [comment]
Or consider installation with `onnxruntime` module all together.

CPU
```shell
$ pip install "rembg[cpu]"
```

GPU
```shell
$ pip install "rembg[gpu]"
```
