### ISSUE TITLE
[FEATURE] Use downloaded model on Cloud Function

### ISSUE THREAD

**Issue by BenjaminRbt** [danielgatis/rembg#638]
First, thanks a lot for this amazing tool!

### Use case

Following the [issue](https://github.com/danielgatis/rembg/issues/363) [@maumarteau](https://github.com/maumarteau) raised, I would like to know if it is planned (or not) to be able to use a given model locally.

In my use case, I use a Google Cloud Function which is hosting a Python script to use this background removal feature. However, when there is no Cloud Function available, it has to start and when it is run, it downloads the model:

```
Downloading data from 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx' to file '/tmp/.u2net/u2net.onnx'.
```

With a progress bar to let us know when it is ready to be used (related sourcecode: [sam.py:275](https://github.com/danielgatis/rembg/blob/main/rembg/sessions/sam.py#L275)).
Once the model is downloaded, the background removal is done and I am able to retrieve a processed image (yay!).

### Problem

Because of this Cloud Function cold start, it requires to wait the model to be download, which is quite long in some use case.
If the Cloud Function is already available, it is quite fast, but the policy to keep awake the Cloud Function does not allow me to keep this Cloud Function for ever.

### Solution

Suggested solution:
- Is it planned to be able to use a local model or not?
- Is it planned to have the ability to specify a path to load the model (for instance in a Google Cloud Storage / Bucket)?

Thanks a lot!

**Comment by ryburke** [comment]
+1 on this feature request. Having the same issue.

**Comment by needl3** [comment]
In short, we were able to download and setup model during docker build. Just made sure we had no issues with the downloaded file and its location, and Pooch used that instead of downloading with no problem.
```python
    os.getenv(
                "U2NET_HOME", os.path.join(os.getenv("XDG_DATA_HOME", "~"), ".u2net")
            )
```
The location priority seems to be the env var `UNET_HOME`, then `$XDG_DATA_HOME/.u2net`, then `$HOME/.u2net`

Just to share my experience here. We also used cloud function with a dockerized workflow and it downloaded every time the container started. The issue, seems to be at the downloaded file itself. We downloaded and saved the model using `curl` but it failed silently after the download completed with downloaded file being 0 bytes. It caused pooch to re download the model since hash is now different. After changing workflow, verifying the download and if built image did contain full model or not, we were able to reuse that downloaded model without further downloads.
