### ISSUE TITLE
Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by yaroslavmavliutov** [danielgatis/rembg#77]
Hello!
Thanks for your project

When i wrote 'from rembg.bg import remove' i got a message 'Expected maxsize to be an integer or None'

**Comment by gbrian** [comment]
Hi, looks promising but same error running as a server

```
 @functools.lru_cache
  raise TypeError('Expected maxsize to be an integer or None')
```
To fix that:
 * User Python3.8 [StackOverflow](https://stackoverflow.com/questions/47218313/use-functools-lru-cache-without-specifying-maxsize-parameter)

BTW if you want to make it work with 3.7 I fixed to test by:
* Apply this https://github.com/danielgatis/rembg/blob/63f52a3a6a7d25edc0828d8a6b0294fdd1e74d71/src/rembg/bg.py#L71
* If you are running as sever fix cmd/server.py

```
import ssl
gcontext = ssl.SSLContext()
file_content = urlopen(unquote_plus(url), context=gcontext).read()
```

DISCLAIMER: this is just a dirty fix in order to make it work and test.

I did and @danielgatis great work! 👏 👏

**Comment by yaroslavmavliutov** [comment]
@gbrian Thanks a lot!

**Comment by linyu0219** [comment]
> Hi, looks promising but same error running as a server
> 
> ```
>  @functools.lru_cache
>   raise TypeError('Expected maxsize to be an integer or None')
> ```
> 
> To fix that:
> 
> * User Python3.8 [StackOverflow](https://stackoverflow.com/questions/47218313/use-functools-lru-cache-without-specifying-maxsize-parameter)
> 
> BTW if you want to make it work with 3.7 I fixed to test by:
> 
> * Apply this https://github.com/danielgatis/rembg/blob/63f52a3a6a7d25edc0828d8a6b0294fdd1e74d71/src/rembg/bg.py#L71
> * If you are running as sever fix cmd/server.py
> 
> ```
> import ssl
> gcontext = ssl.SSLContext()
> file_content = urlopen(unquote_plus(url), context=gcontext).read()
> ```
> 
> DISCLAIMER: this is just a dirty fix in order to make it work and test.
> 
> I did and @danielgatis great work! clap clap

works niubi
